# Generated by Django 5.1.7 on 2025-03-20 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forumcategory_forumthread_forumpost_group_post_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='created_by',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('creator', 'Creator')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
    ]
