# Generated by Django 5.1.7 on 2025-03-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_created_by_group_creator_remove_group_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='restrict_to_group',
            field=models.BooleanField(default=False),
        ),
    ]
