# Generated by Django 5.1.7 on 2025-03-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='PlayerProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('woodcutting_xp', models.BigIntegerField(default=0)),
                ('mining_xp', models.BigIntegerField(default=0)),
                ('fishing_xp', models.BigIntegerField(default=0)),
                ('cooking_xp', models.BigIntegerField(default=0)),
                ('smithing_xp', models.BigIntegerField(default=0)),
                ('attack_xp', models.BigIntegerField(default=0)),
                ('strength_xp', models.BigIntegerField(default=0)),
                ('defence_xp', models.BigIntegerField(default=0)),
                ('hitpoints_xp', models.BigIntegerField(default=10000)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
