# Generated by Django 5.1.7 on 2025-03-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spircre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('user_id', 'item_name')},
            },
        ),
    ]
