# Generated by Django 5.1.7 on 2025-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spircre', '0002_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highscore',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
