from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('images/', views.images, name='images'),
    path('videos/', views.videos, name='videos'),
    path('audio/', views.audio, name='audio'),
    path('text-links/', views.text_links, name='text_links'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('upload/', views.upload_post, name='upload_post'),
    path('post/vote/<int:post_id>/<str:vote_type>/', views.vote_post, name='vote_post'),
    path('comment/vote/<int:comment_id>/<str:vote_type>/', views.vote_comment, name='vote_comment'),
    path('post/hide/<int:post_id>/', views.hide_post, name='hide_post'),
    path('post/delete/<int:post_id>/', views.perm_delete_post, name='perm_delete_post'),
    path('comment/hide/<int:comment_id>/', views.hide_comment, name='hide_comment'),
    path('comment/delete/<int:comment_id>/', views.perm_delete_comment, name='perm_delete_comment'),
    path('comment/<int:comment_id>/', views.direct_comment, name='direct_comment'),
    path('comment/reply/<int:comment_id>/', views.reply_comment, name='reply_comment'),
    path('mod-panel/', views.mod_panel, name='mod_panel'),
    path('groups/', views.group_list, name='group_list'),
    path('groups/create/', views.group_create, name='group_create'),
    path('groups/<int:group_id>/', views.group_detail, name='group_detail'),
    path('groups/<int:group_id>/join/', views.group_join, name='group_join'),
    path('groups/<int:group_id>/leave/', views.group_leave, name='group_leave'),
    path('groups/<int:group_id>/moderate/', views.group_moderate, name='group_moderate'),
    path('groups/<int:group_id>/post/', views.group_post, name='group_post'),
    path('forums/', views.forums, name='forums'),
    path('forums/create/', views.create_forum, name='create_forum'),
    path('forums/<str:forum_slug>/', views.forum_detail, name='forum_detail'),
    path('forums/<str:forum_slug>/create_post/', views.create_forum_post, name='create_forum_post'),
    path('forums/<str:forum_slug>/post/<int:post_id>/', views.forum_post_detail, name='forum_post_detail'),
    path('forums/<str:forum_slug>/post/<int:post_id>/replies/', views.forum_post_replies, name='forum_post_replies'),
]